# Generated by Django 5.2.5 on 2025-09-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0006_merge_20250904_1555'),
        ('enrollments', '0003_contentbundle_contenttype_videoenrollment_and_more'),
        ('payments', '0002_remove_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='enrollments.contentbundle'),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contentbundle',
            name='content_items',
            field=models.ManyToManyField(related_name='bundles', to='enrollments.contenttype'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='enrollments.contenttype'),
        ),
        migrations.AddField(
            model_name='videoenrollment',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_details', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='videoenrollment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.video'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
    ]
