# Generated by Django 5.2.5 on 2025-08-28 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(help_text='Stripe PaymentIntent ID', max_length=100, null=True, unique=True)),
                ('stripe_payment_method_id', models.CharField(help_text='Stripe PaymentMethod ID', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Payment Pending'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment/order metadata')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
