# Generated by Django 4.2.14 on 2025-08-31 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], max_length=20, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='accounts.teacherprofile')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_platform', models.CharField(choices=[('zoom', 'Zoom'), ('meet', 'Google Meet')], default='zoom', max_length=20)),
                ('meeting_url', models.URLField(blank=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('meeting_password', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('student_notes', models.TextField(blank=True, help_text='Notes from student about what they want to cover')),
                ('teacher_notes', models.TextField(blank=True, help_text="Teacher's notes about the session")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='live_sessions.timeslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['start_time', 'is_available'], name='live_sessio_start_t_8d136f_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['teacher', 'is_available'], name='live_sessio_teacher_526aec_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['status', 'created_at'], name='live_sessio_status_0351fc_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['student', 'status'], name='live_sessio_student_9dd5e0_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['course', 'status'], name='live_sessio_course__7d997c_idx'),
        ),
    ]
