# Generated by Django 4.2.14 on 2025-09-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial_content_models'),
        ('courses', '0002_course_content_types'),
        ('courses', '0002_delete_enrollment'),
        ('courses', '0003_assignment_submission_assignmentfeedback_and_more'),
        ('courses', '0005_remove_abstract_from_models'),
    ]

    operations = [
    ]
