# Generated by Django 4.2.14 on 2025-08-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('enrollments.enrollment',),
        ),
    ]
